name: ci-golang-workflow
on: 
  pull_request:
    branches: 
      - develop

jobs: 
  check-application:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix: 
    #     go:  ['1.15']
  
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with: 
          go-version: '1.15'
      - run: go test -coverprofile=coverage.out
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        